version: '2.2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ${ES_DATA}:/usr/share/elasticsearch/data
    mem_limit: 1024M
    memswap_limit: 1024M
    # CPU 利用率权重,默认为 1024，
    cpu_shares: 1024
    # 100% CPU
    cpu_period: 100000
    cpu_quota: 200000
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    mem_limit: 1024M
    memswap_limit: 1024M
    # CPU 利用率权重,默认为 1024，
    cpu_shares: 512
    # 100% CPU
    cpu_period: 100000
    cpu_quota: 100000
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:$ELK_VERSION
    user: root
    links:
      - elasticsearch
    volumes:
      - ./filebeat/config/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - ${LOGS_DIR}:/filebeat/logs
    mem_limit: 1024M
    memswap_limit: 1024M
    # CPU 利用率权重,默认为 1024，
    cpu_shares: 512
    # 100% CPU
    cpu_period: 100000
    cpu_quota: 100000
    command: filebeat -e -strict.perms=false -E output.elasticsearch.hosts=["elasticsearch:9200"]
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
